const styles = {
  container: {
    width: "100%",
    maxWidth: "1446px",
    margin: "0 auto",
    position: "relative",
  },
  header: {
    width: "1446px",
    height: "206px",
    top: "20px",
    left: "33px",
    borderRadius: "24px 24px 24px 24px",
    background:
      "linear-gradient(90deg, #D93100 0.86%, #000000 48.98%, #D93100 100%)",
    position: "relative",
  },
  eliteLogo: {
    position: "absolute",
    top: "1px",
    left: "10px",
    width: "100px",
    height: "100px",
    filter: "brightness(0) invert(1)",
  },
  logoPlaceholder: {
    position: "absolute",
    top: "1px",
    right: "10px",
    width: "80px",
    height: "auto",
  },
  headerText: {
    position: "absolute",
    top: "50%",
    left: "400px",
    transform: "translate(-50%, -50%)",
    width: "575px",
    height: "108px",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "center",
  },
  findYour: {
    fontFamily: "Rugen, sans-serif",
    fontSize: "40.17px",
    fontWeight: 400,
    lineHeight: "46.2px",
    color: "transparent",
    WebkitTextStroke: "1px white",
    marginBottom: "5px",
  },
  dreamJob: {
    fontFamily: "Rugen, sans-serif",
    fontSize: "65px",
    fontWeight: 400,
    lineHeight: "74.75px",
    color: "white",
  },
  starPlaceholder: {
    position: "absolute",
    top: "10px",
    right: "10px",
    color: "white",
  },
  searchContainer: {
    width: "566px",
    height: "63px",
    top: "321px",
    left: "296px",
    position: "absolute",
    display: "flex",
    alignItems: "center",
    background: "#F9F9F9",
    borderRadius: "24px 24px 9px 9px",
    border: "1px solid #D93100",
  },
  searchInput: {
    width: "100%",
    height: "100%",
    borderRadius: "24px 24px 9px 9px",
    padding: "0 20px",
    fontSize: "16px",
    fontFamily: "Inter, sans-serif",
    color: "#FB6438",
    border: "none",
    outline: "none",
    placeholderColor: "#FB6438",
  },
  searchIcon: {
    width: "17.74px",
    height: "17.74px",
    color: "#FB6438",
    marginRight: "20px",
  },
  searchButton: {
    width: "157px",
    height: "63px",
    position: "absolute",
    right: "-170px",
    borderRadius: "24px 24px 9px 9px",
    background: "#D93100",
    color: "white",
    border: "none",
    cursor: "pointer",
    fontFamily: "Inter, sans-serif",
    fontSize: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  mainContent: {
    display: "flex",
    marginTop: "100px",
  },
  leftSidebar: {
    width: "246px",
    height: "800px",
    borderRadius: "21px 21px 21px 21px",
    boxShadow: "0px 8px 4px 0px #00000040",
    padding: "20px",
    color: "#FB6438",
  },
  filtersHeader: {
    display: "flex",
    alignItems: "center",
    marginBottom: "20px",
    color: "#FB6438",
  },
  filterLines: {
    width: "16px",
    height: "9.5px",
    background: "#DA3201",
    marginRight: "10px",
  },
  filtersText: {
    fontFamily: "Inter, sans-serif",
    fontSize: "13px",
    fontWeight: 700,
    color: "#D93100",
    marginBottom: "10px",
  },
  clearAllText: {
    fontFamily: "Inter, sans-serif",
    fontSize: "13px",
    fontWeight: 700,
    color: "#DBA596",
    marginLeft: "auto",
    cursor: "pointer",
  },
  filterBox: {
    width: "203px",
    border: "1px ",
    borderRadius: "23px 23px 23px 23px",
    boxShadow: "0px 4px 4px 0px #00000040",
    padding: "10px",
    marginBottom: "20px",
  },
  filterItem: {
    display: "flex",
    alignItems: "center",
    marginBottom: "5px",
    color: "#FB6438",
  },
  checkbox: {
    width: "14px",
    height: "14px",
    accentColor: "#D93100",
    marginRight: "5px",
    border: "1px solid #D93100",
    borderRadius: "2px",
  },
  middleSection: {
    flex: 1,
    padding: "0 20px",
  },
  jobCard: {
    width: "920px",
    height: "171px",
    boxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.25)",
    padding: "20px",
    border: "none",
    marginBottom: "20px",
    position: "relative",
    display: "flex",
    alignItems: "center",
    fontFamily: "Inter, sans-serif",
  },
  jobCardOrangeBox: {
    width: "188px",
    height: "155px",
  },
  jobTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    color: "#D93100",
  },
  vectorIcon: {
    width: "13px",
    height: "111px",
    position: "absolute",
    top: "564px",
    left: "512px",
    opacity: "0",
  },
  applyButton: {
    width: "120px",
    height: "40px",
    position: "absolute",
    bottom: "20px",
    right: "20px",
    borderRadius: "10px",
    boxShadow: "0px 14px 14px 0px #00000040",
    background: "linear-gradient(96.25deg, #D93100 23.41%, #962201 125.67%)",
    color: "white",
    border: "none",
    cursor: "pointer",
    fontFamily: "Inter, sans-serif",
    fontSize: "15px",
    textDecoration: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  rightSidebar: {
    width: "246px",
    height: "450px",
    borderRadius: "21px 21px 21px 21px",
    background: "#FFFFFF",
    boxShadow: "0px 4px 4px 0px #00000040",
    padding: "20px",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    justifyContent: "center",
  },
  terLogoPlaceholder: {
    marginBottom: "20px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  separator: {
    width: "204px",
    height: "0px",
    border: "0.7px solid #282828",
    margin: "20px 0",
  },
  rightSidebarText: {
    width: "203px",
    height: "85px",
    marginBottom: "20px",
    fontFamily: "Inter, sans-serif",
  },
  stayAheadText: {
    fontSize: "16px",
    fontStyle: "italic",
    color: "#000000",
  },
  aheadText: {
    color: "#D93100", // Orange color
  },
  newRolesText: {
    color: "#D93100", // Orange color
  },
  rightSidebarTextItalic: {
    color: "#D93100", // Color for 'AHEAD'
  },
  teamImage: {
    width: "228px",
    height: "139px",
    objectFit: "cover",
  },
};

export default styles;
